apiVersion: v1
kind: ConfigMap
metadata:
  name: shippig
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippig
  namespace: roboshop
  labels:
    project: roboshop
    component: shippig
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shippig
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: shippig
        tier: backend
    spec:
      containers:
      - name: shippig
        image: suryamalli/shippig:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shippig
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shippig
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: shippig
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port 